### ISSUE TITLE
Remove errornous version number on anaconda.org

### ISSUE THREAD

**Issue by petrushy** [conda-forge/orekit-feedstock#29]
There is an erroneous formatted version number at anaconda.org, 10_0_4. This version should be removed as it now has priority over other newer versions and is except for version number same as 10.0.4.

Not sure this is the right place to put this issue :)

Many thanks

**Comment by petrushy** [comment]
Hi @conda-forge/core, could you please remove the 10_0_4 version from the anaconda.org?

**Comment by scopatz** [comment]
Set to broken

**Comment by petrushy** [comment]
Thanks!
